### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [petioptrv/movement_detector#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.3. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary movement-detector -w /tmp/ext movement-detector==0.2.3
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting movement-detector==0.2.3
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/4b7/433f013276db0/movement-detector-0.2.3.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ghrr7ddr/movement-detector/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ghrr7ddr/movement-detector/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ghrr7ddr/movement-detector/pip-egg-info
         cwd: /tmp/pip-wheel-ghrr7ddr/movement-detector/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ghrr7ddr/movement-detector/setup.py", line 44, in <module>
        with open(THIS_DIR / 'LICENSE.txt', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-ghrr7ddr/movement-detector/LICENSE.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by petioptrv** [comment]
Hey @thatch, thanks for the contribution! I reverted some of my recent C++ experiments and put them in a branch, so I think I messed up a bit your PR, but I push your changes just now.

Btw, out of curiosity, how did you end up on this package?

**Comment by thatch** [comment]
I'm going though all ~84k pypi projects updated in the last year. Sorry, nothing specific to yours.
